version: '3.8'

services:
  queue:
    build: ./rabbitmq
    ports:
      - 15672:15672
      - 1883:1883
      - 5672:5672
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  db:
    build: ./db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  db_writer:
    build: ./db_writer
    ports:
      - "5678:5678"
    env_file:
      - .env
    environment:
      - RABBITMQ_HOST=queue
      - PYTHONUNBUFFERED=1
      - DB_HOST=db
    depends_on:
      - queue
      - db
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

  web:
    build: ./web
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      - RABBITMQ_HOST=queue
      - DB_HOST=db
    depends_on:
      - queue
      - db

volumes:
  pg_data: