version: '3.8'

services:
  queue:
    build: ./rabbitmq
    ports:
      - 15672:15672
      - 1883:1883
      - 5672:5672

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql