version: '3.8'

services:
  queue:
    build: ./rabbitmq
    ports:
      - 15672:15672
      - 1883:1883
      - 5672:5672

  db:
    build: ./db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres

  db_writer:
    build: ./db_writer
    ports:
      - "5678:5678"
    environment:
      - RABBITMQ_HOST=queue
      - PYTHONUNBUFFERED=1
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
    depends_on:
      - queue
      - db
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

  web:
    build: ./web
    ports:
      - "80:80"
    environment:
      - RABBITMQ_HOST=queue
    depends_on:
      - queue