version: '3.8'

services:
  zero:
    build: ./zero
    ports:
      - "5678:5678"
    env_file:
      - .env.default
    environment:
      - RABBITMQ_HOST=192.168.11.11
      - PYTHONUNBUFFERED=1
      - DEVICE_ID=zero
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure