version: '3.8'

services:
  queue:
    build: ./rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  db:
    build: ./db
    ports:
      - "5432:5432"
    env_file:
      - .env.default
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  db_writer:
    build: ./db_writer
    ports:
      - "5678:5678"
    env_file:
      - .env.default
      - .env
    environment:
      - RABBITMQ_HOST=queue
      - PYTHONUNBUFFERED=1
      - DB_HOST=db
    depends_on:
      - queue
      - db
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  web:
    build: ./web
    ports:
      - "80:80"
    env_file:
      - .env.default
      - .env
    environment:
      - RABBITMQ_HOST=queue
      - DB_HOST=db
    depends_on:
      - queue
      - db
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  pg_data:
