name: Build and push to Docker Hub

on:
  push:
    branches:
      - "main"
      - "testcontainers"
      - "net7"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm'
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push Zero
        uses: docker/build-push-action@v4
        with:
          context: zero
          platforms: linux/arm/v7
          file: ./zero/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/iot-rabbitmq:latest      
      -
        name: Build and push rabbitmq
        uses: docker/build-push-action@v4
        with:
          context: rabbitmq
          platforms: linux/arm/v7
          file: ./rabbitmq/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/iot-rabbitmq:latest
      -
        name: Build and push Web
        uses: docker/build-push-action@v4
        with:
          context: web
          file: ./web/Dockerfile.armv7
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/iot-web:latest
      -
        name: Build and push Db
        uses: docker/build-push-action@v4
        with:
          context: db
          platforms: linux/arm/v7
          file: ./db/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/iot-db:latest
      -
        name: Build and push Db optimizer
        uses: docker/build-push-action@v4
        with:
          context: db_optimizer
          platforms: linux/arm/v7
          file: ./db_optimizer/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/iot-db-optimizer:latest
      -
        name: Build and push Db writer
        uses: docker/build-push-action@v4
        with:
          context: db_writer
          platforms: linux/arm/v7
          file: ./db_writer/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/iot-db-writer:latest